dist: trusty
sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libev-dev

compiler:
  - gcc

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build/onion
  - cd build/onion && cmake -DCMAKE_INSTALL_PREFIX=$HOME ../../onion && make && make install
  - cd $HOME && ls -la

script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build/fastcci
  - cd build/fastcci && cmake -DCMAKE_PREFIX_PATH=$HOME ../.. && make
