dist: trusty
sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libev-dev

compiler:
  - gcc

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build/onion
  - cd build/onion && cmake -DCMAKE_INSTALL_PREFIX=$HOME ../../onion && make && make install

script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build/fastcci
  - export CXXFLAGS="-I $HOME/include -L $HOME/lib"
  - cd build/fastcci && cmake -DCMAKE_PREFIX_PATH=$HOME ../.. && make
  - cd $TRAVIS_BUILD_DIR/test && ./runtests.sh
